Repository spdx/tools-java, pull requests merged in 2025-04, with the labels that each got.

#194 Add a test- case to flag if the JSON Schema file need to be updated
  resources/spdx-schema-v3.0.1.json
  src/test/java/org/spdx/tools/LatestSchemaVersionTest.java
Labels: enhancement

#198 Update SPDX libraries version in POM
  pom.xml
Labels: dependencies

#197 Use URI.create().toURL() instead of the deprecated URL() constructor
  src/test/java/org/spdx/tools/LatestSchemaVersionTest.java
Labels: test

#199 Normalize whitespace in schema compare unit test
  src/test/java/org/spdx/tools/LatestSchemaVersionTest.java
Labels: bug, test

#200 spdx-maven-plugin == 1.0.0
  pom.xml
Labels: dependencies

#202 Fix Shade plugin version to 3.2.4
  pom.xml
Labels: dependencies

#203 Update JAR name in command line examples to 2.0.0
  README.md
Labels: documentation

#205 Update README examples with new release versions
  README.md
Labels: documentation
